name: Update Static Files
run-name: Updating the Frame 🖼️🚀
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: 

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update static files
        run: |
          python3 update_static_files.py

      - name: Commit and push changes
        run: |
          git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
          git config --global user.email '${{ env.CI_COMMIT_EMAIL }}'
          git add .
          git commit -m 'Automated update of static files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
